# Generated by Django 5.0.1 on 2024-12-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='imagem',
            field=models.ImageField(default='salas/logo.png', upload_to='salas/'),
        ),
    ]
