# Generated by Django 5.0.1 on 2024-12-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_configuracaosistema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoSistema',
        ),
    ]
