# Generated by Django 5.0.1 on 2025-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_configuracaosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='limite_reservas_por_usuario',
            field=models.PositiveIntegerField(blank=True, help_text='Defina um limite diário de reservas por usuário. Deixe em branco para não ter limite.', null=True),
        ),
    ]
